### ISSUE TITLE
Fix your eportfolio lmao

### ISSUE THREAD

**Issue by BartWolters21** [daanvhekken/daanvhekken.github.io#8]
Ever since 2019 or 20, all I hear everyday is Minecraft. I liked Minecraft when I was 7, but I wasn't obsessed with it and I didn't grow crushes on these Minecraft YouTubers. There's a group of YouTubers which call themselves the DreamSMP, and every single person I know is obsessed with them, shipping the members of the group, and it's really annoying. I wake up and go on a group chat just to hear about a new "Minecraft snapshot" or "OMG DID YOU SEE THE NEW VIDEO BY GEORGE WAS FOUND", at one point my friends got into an argument with me that the acronym DNF means Dream Not Found which is a ship between two of the YouTubers of that DreamSMP group. Now acronyms can have multiple meanings, but they refused to believe that DNF also means "Did Not Finish". And can somebody tell me why I keep hearing about this Highpixel server? I ask somebody if they wanna join me on Battlefield 4 and they decline and ask if I wanna join them on Highpixel, I hear this word everyday. Highpixel, highpixel, highpixel. I ask him what the game Highpixel is about because I hear it everywhere I go, and he tells me it's a Minecraft server. I ended the call, that was like my friend telling me he does drugs. I don't own Minecraft, and why would I pay $50 for a game about putting down blocks and killing spiders? I may as well do that in real life! But you're probably thinking "These are the reasons you think Minecraft is overrated? You must be an idiot." But the full reason that I'm basically against it is because it's the only thing people play these days. Wanna play Battlefield? "How about Minecraft?" Wanna play Watch Dogs 2? "No, but I'm playing Minecraft right now if you wanna join." Wanna play Roblox? That's a bit like Minecraft? "No, Minecraft is way better than Roblox." So yeah, Minecraft is overrated.

**Comment by owenselles** [comment]
I agree 100% with this

**Comment by daanvhekken** [comment]
Agreed.

**Comment by BartWolters21** [comment]
I have a chungus kink. My boyfriend knows about it and for the most part, he accepts it, but I have the feeling that he isn't really enthusiastic about it and doesn't really get it but he at least tries to, which I am grateful for. He'll sometimes sing the BIG CHUNGUS THEME SONG to me to set the mood, or if he is really kinky he would tell me "You're a real chungus" in the heat of the moment.

The thing is, I don't want to hear the chungus theme song or look at big chungus. I want to be fucked by the damn rabbit. And for the record, this is common among women. Chungus's perfect fur to me (and many others) is what a Mack truck is to Cardi B.

My boyfriend asked if I wanted to go to a chungus convention and I told him straight up. I told him to put the chungus fursuit on, kidnap me from my bed, take me to the convention and ravage me in front of everyone.

He flat-out refused. I was literally begging this man to do it. He said that this was too weird for him and that we shouldn't talk for a while...

I don't want to lose him over my chungus fetish, but it is hard for me to drop one of my sexual desires. Should i try to make a compromise with him, or do i simply need a more adventurous man?

Thank you for reading.

**Comment by BartWolters21** [comment]
@daanvhekken @owenselles

**Comment by owenselles** [comment]
This website is so bad the design is so badly done it's getting ripped apart. A lot of it makes the page just look ugly - nothing much in it, no detail, no details in it, nothing for a reason. And I thought that the author was going to do another piece of bad design in there too, but it's the same person. For all the poor design that they tried to avoid I wish I were in their shoes (if it's a good piece of bad design it'll be perfect!
